[package]
name = "bmp"
version = "0.1.0"
authors = ["kame_local <Kamekamekame7@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
